/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: PersonReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  location?: LocationReference;
  publishedAt?: string;
  body?: BlockContent;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  address?: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
  };
  geolocation?: Geopoint;
  description?: BlockContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Category
  | PersonReference
  | CategoryReference
  | LocationReference
  | Post
  | Location
  | SanityImageCrop
  | SanityImageHotspot
  | Geopoint
  | Slug
  | Person
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/app/authors/[slug]/page.tsx
// Variable: AUTHOR_QUERY
// Query: *[_type == "person" && slug.current == $slug][0] {    name,    bio,    "image": image.asset->url,    "posts": *[_type == "post" && author._ref == ^._id] | order(publishedAt desc) {      _id,      title,      slug,      publishedAt,      "mainImage": mainImage.asset->url    }  }
export type AUTHOR_QUERY_RESULT = {
  name: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: string | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    mainImage: string | null;
  }>;
} | null;

// Source: ../web/src/app/categories/[slug]/page.tsx
// Variable: CATEGORY_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    title,    description,    "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {      _id,      title,      slug,      publishedAt,      "mainImage": mainImage.asset->url    }  }
export type CATEGORY_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    mainImage: string | null;
  }>;
} | null;

// Source: ../web/src/app/categories/page.tsx
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    slug,    description,    "postCount": count(*[_type == "post" && references(^._id)])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: null;
  description: string | null;
  postCount: number;
}>;

// Source: ../web/src/app/locations/[slug]/page.tsx
// Variable: LOCATION_QUERY
// Query: *[_type == "location" && slug.current == $slug][0] {    name,    address,    "image": image.asset->url,    "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {      _id,      title,      slug,      publishedAt,      "mainImage": mainImage.asset->url    }  }
export type LOCATION_QUERY_RESULT = {
  name: string | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
  } | null;
  image: string | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    mainImage: string | null;
  }>;
} | null;

// Source: ../web/src/app/locations/page.tsx
// Variable: LOCATIONS_QUERY
// Query: *[_type == "location"] | order(name asc) {    _id,    name,    slug,    address,    "image": image.asset->url,    "postCount": count(*[_type == "post" && references(^._id)])  }
export type LOCATIONS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
  } | null;
  image: string | null;
  postCount: number;
}>;

// Source: ../web/src/app/page.tsx
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc)[0...12] {    _id,    title,    slug,    publishedAt,    "author": author->{name, slug, "image": image.asset->url},    "location": location->{name, slug, "image": image.asset->url},    "mainImage": mainImage.asset->url,    "categories": categories[]->{title, slug}  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    slug: Slug | null;
    image: string | null;
  } | null;
  location: {
    name: string | null;
    slug: Slug | null;
    image: string | null;
  } | null;
  mainImage: string | null;
  categories: Array<{
    title: string | null;
    slug: null;
  }> | null;
}>;

// Source: ../web/src/app/posts/[slug]/page.tsx
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    slug,    publishedAt,    "author": author->{name, slug},    "location": location->{name, slug},    "mainImage": mainImage.asset->url,    "categories": categories[]->{title, slug},    body  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    slug: Slug | null;
  } | null;
  location: {
    name: string | null;
    slug: Slug | null;
  } | null;
  mainImage: string | null;
  categories: Array<{
    title: string | null;
    slug: null;
  }> | null;
  body: BlockContent | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "person" && slug.current == $slug][0] {\n    name,\n    bio,\n    "image": image.asset->url,\n    "posts": *[_type == "post" && author._ref == ^._id] | order(publishedAt desc) {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      "mainImage": mainImage.asset->url\n    }\n  }\n': AUTHOR_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    title,\n    description,\n    "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      "mainImage": mainImage.asset->url\n    }\n  }\n': CATEGORY_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    slug,\n    description,\n    "postCount": count(*[_type == "post" && references(^._id)])\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "location" && slug.current == $slug][0] {\n    name,\n    address,\n    "image": image.asset->url,\n    "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      "mainImage": mainImage.asset->url\n    }\n  }\n': LOCATION_QUERY_RESULT;
    '\n  *[_type == "location"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    address,\n    "image": image.asset->url,\n    "postCount": count(*[_type == "post" && references(^._id)])\n  }\n': LOCATIONS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc)[0...12] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    "author": author->{name, slug, "image": image.asset->url},\n    "location": location->{name, slug, "image": image.asset->url},\n    "mainImage": mainImage.asset->url,\n    "categories": categories[]->{title, slug}\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    "author": author->{name, slug},\n    "location": location->{name, slug},\n    "mainImage": mainImage.asset->url,\n    "categories": categories[]->{title, slug},\n    body\n  }\n': POST_QUERY_RESULT;
  }
}
