/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sections?: Array<
    | {
        title?: string;
        subtitle?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "hero";
        _key: string;
      }
    | {
        title?: string;
        subtitle?: string;
        _type: "moodPicker";
        _key: string;
      }
    | {
        title?: string;
        count?: number;
        _type: "featuredPosts";
        _key: string;
      }
    | {
        heading?: string;
        content?: BlockContent;
        align?: "left" | "center" | "right";
        _type: "textContent";
        _key: string;
      }
  >;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SiteConfig = {
  _id: string;
  _type: "siteConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  headerNav?: Array<{
    title?: string;
    linkType?: "internal" | "external";
    internalLink?: CategoryReference | LocationReference | PageReference;
    externalLink?: string;
    _type: "navItem";
    _key: string;
  }>;
  footerText?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: BlockContent;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type MoodReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mood";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: PersonReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageUrl?: string;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  mood?: MoodReference;
  location?: LocationReference;
  publishedAt?: string;
  body?: BlockContent;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageUrl?: string;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
  };
  geolocation?: Geopoint;
  description?: BlockContent;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Mood = {
  _id: string;
  _type: "mood";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  colorStart?: string;
  colorEnd?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageUrl?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | HomePage
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | CategoryReference
  | LocationReference
  | PageReference
  | SiteConfig
  | Page
  | Slug
  | Category
  | PersonReference
  | MoodReference
  | Post
  | Location
  | Geopoint
  | Mood
  | Person
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/app/[slug]/page.tsx
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    title,    body,    "imageUrl": mainImage.asset->url  }
export type PAGE_QUERY_RESULT = {
  title: string | null;
  body: BlockContent | null;
  imageUrl: string | null;
} | null;

// Source: ../web/src/app/authors/[slug]/page.tsx
// Variable: AUTHOR_QUERY
// Query: *[_type == "person" && slug.current == $slug][0] {    name,    bio,    "image": image.asset->url,    imageUrl,    "posts": *[_type == "post" && author._ref == ^._id] | order(publishedAt desc) {      _id,      title,      slug,      publishedAt,      "mainImage": mainImage.asset->url,      imageUrl    }  }
export type AUTHOR_QUERY_RESULT = {
  name: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: string | null;
  imageUrl: string | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    mainImage: string | null;
    imageUrl: string | null;
  }>;
} | null;

// Source: ../web/src/app/categories/[slug]/page.tsx
// Variable: CATEGORY_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    title,    description,    "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {      _id,      title,      slug,      publishedAt,      "mainImage": mainImage.asset->url,      imageUrl    }  }
export type CATEGORY_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    mainImage: string | null;
    imageUrl: string | null;
  }>;
} | null;

// Source: ../web/src/app/categories/page.tsx
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "postCount": count(*[_type == "post" && references(^._id)])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: null;
  description: string | null;
  postCount: number;
}>;

// Source: ../web/src/app/layout.tsx
// Variable: SITE_CONFIG_QUERY
// Query: *[_id == "siteConfig"][0] {    title,    footerText,    headerNav[] {      title,      linkType,      externalLink,      "internalLink": internalLink-> {        _type,        "slug": slug.current      }    }  }
export type SITE_CONFIG_QUERY_RESULT =
  | {
      title: null;
      footerText: null;
      headerNav: null;
    }
  | {
      title: string | null;
      footerText: null;
      headerNav: null;
    }
  | {
      title: string | null;
      footerText: string | null;
      headerNav: Array<{
        title: string | null;
        linkType: "external" | "internal" | null;
        externalLink: string | null;
        internalLink:
          | {
              _type: "category";
              slug: null;
            }
          | {
              _type: "location";
              slug: string | null;
            }
          | {
              _type: "page";
              slug: string | null;
            }
          | null;
      }> | null;
    }
  | null;

// Source: ../web/src/app/locations/[slug]/page.tsx
// Variable: LOCATION_QUERY
// Query: *[_type == "location" && slug.current == $slug][0] {    name,    address,    geolocation,    description,    "image": image.asset->url,    imageUrl,    "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {      _id,      title,      slug,      publishedAt,      "mainImage": mainImage.asset->url,      imageUrl    }  }
export type LOCATION_QUERY_RESULT = {
  name: string | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
  } | null;
  geolocation: Geopoint | null;
  description: BlockContent | null;
  image: string | null;
  imageUrl: string | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    mainImage: string | null;
    imageUrl: string | null;
  }>;
} | null;

// Source: ../web/src/app/locations/page.tsx
// Variable: LOCATIONS_QUERY
// Query: *[_type == "location"] | order(name asc) {    _id,    name,    slug,    address,    "image": image.asset->url,    imageUrl,    "postCount": count(*[_type == "post" && references(^._id)])  }
export type LOCATIONS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  address: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
  } | null;
  image: string | null;
  imageUrl: string | null;
  postCount: number;
}>;

// Source: ../web/src/app/page.tsx
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0] {    title,    sections[] {      _type,      _key,      _type == "hero" => {        title,        subtitle,        "imageUrl": image.asset->url      },      _type == "moodPicker" => {        title,        subtitle      },      _type == "featuredPosts" => {        title,        count      },      _type == "textContent" => {        heading,        content,        align      }    },    seo  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      title: null;
      sections: null;
      seo: null;
    }
  | {
      title: string | null;
      sections: null;
      seo: null;
    }
  | {
      title: string | null;
      sections: Array<
        | {
            _type: "featuredPosts";
            _key: string;
            title: string | null;
            count: number | null;
          }
        | {
            _type: "hero";
            _key: string;
            title: string | null;
            subtitle: string | null;
            imageUrl: string | null;
          }
        | {
            _type: "moodPicker";
            _key: string;
            title: string | null;
            subtitle: string | null;
          }
        | {
            _type: "textContent";
            _key: string;
            heading: string | null;
            content: BlockContent | null;
            align: "center" | "left" | "right" | null;
          }
      > | null;
      seo: {
        metaTitle?: string;
        metaDescription?: string;
      } | null;
    }
  | null;

// Source: ../web/src/app/page.tsx
// Variable: INITIAL_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc, _id desc)[0...12] {    _id,    title,    slug,    publishedAt,    "author": author->{_id, name, slug, "image": image.asset->url, imageUrl},    "location": location->{_id, name, slug, "image": image.asset->url, imageUrl},    "mainImage": mainImage.asset->url,    imageUrl,    "categories": categories[]->{_id, title, "slug": slug.current},    "mood": mood->{_id, title, slug, colorStart, colorEnd}  }
export type INITIAL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    image: string | null;
    imageUrl: string | null;
  } | null;
  location: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    image: string | null;
    imageUrl: string | null;
  } | null;
  mainImage: string | null;
  imageUrl: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: null;
  }> | null;
  mood: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    colorStart: string | null;
    colorEnd: string | null;
  } | null;
}>;

// Source: ../web/src/app/page.tsx
// Variable: MOODS_QUERY
// Query: *[_type == "mood"] | order(title asc) {    _id,    title,    slug,    description,    colorStart,    colorEnd  }
export type MOODS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  colorStart: string | null;
  colorEnd: string | null;
}>;

// Source: ../web/src/app/posts/[slug]/page.tsx
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    slug,    publishedAt,    "author": author->{_id, name, slug, "image": image.asset->url, imageUrl},    "location": location->{_id, name, slug, "image": image.asset->url, imageUrl},    "mainImage": mainImage.asset->url,    imageUrl,    "categories": categories[]->{_id, title, "slug": slug.current},    "mood": mood->{_id, title, colorStart, colorEnd},    body  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    image: string | null;
    imageUrl: string | null;
  } | null;
  location: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    image: string | null;
    imageUrl: string | null;
  } | null;
  mainImage: string | null;
  imageUrl: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: null;
  }> | null;
  mood: {
    _id: string;
    title: string | null;
    colorStart: string | null;
    colorEnd: string | null;
  } | null;
  body: BlockContent | null;
} | null;

// Source: ../web/src/app/posts/[slug]/page.tsx
// Variable: SIMILAR_POSTS_QUERY
// Query: *[_type == "post" && slug.current != $slug && (    author._ref == $authorId ||     location._ref == $locationId ||     count(categories[@._ref in $categoryIds]) > 0  )] | order(publishedAt desc)[0...3] {    _id,    title,    slug,    publishedAt,    "mainImage": mainImage.asset->url,    imageUrl,    "mood": mood->{_id, title, colorStart, colorEnd}  }
export type SIMILAR_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImage: string | null;
  imageUrl: string | null;
  mood: {
    _id: string;
    title: string | null;
    colorStart: string | null;
    colorEnd: string | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    title,\n    body,\n    "imageUrl": mainImage.asset->url\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "person" && slug.current == $slug][0] {\n    name,\n    bio,\n    "image": image.asset->url,\n    imageUrl,\n    "posts": *[_type == "post" && author._ref == ^._id] | order(publishedAt desc) {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      "mainImage": mainImage.asset->url,\n      imageUrl\n    }\n  }\n': AUTHOR_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    title,\n    description,\n    "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      "mainImage": mainImage.asset->url,\n      imageUrl\n    }\n  }\n': CATEGORY_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "postCount": count(*[_type == "post" && references(^._id)])\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_id == "siteConfig"][0] {\n    title,\n    footerText,\n    headerNav[] {\n      title,\n      linkType,\n      externalLink,\n      "internalLink": internalLink-> {\n        _type,\n        "slug": slug.current\n      }\n    }\n  }\n': SITE_CONFIG_QUERY_RESULT;
    '\n  *[_type == "location" && slug.current == $slug][0] {\n    name,\n    address,\n    geolocation,\n    description,\n    "image": image.asset->url,\n    imageUrl,\n    "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      "mainImage": mainImage.asset->url,\n      imageUrl\n    }\n  }\n': LOCATION_QUERY_RESULT;
    '\n  *[_type == "location"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    address,\n    "image": image.asset->url,\n    imageUrl,\n    "postCount": count(*[_type == "post" && references(^._id)])\n  }\n': LOCATIONS_QUERY_RESULT;
    '\n  *[_id == "homePage"][0] {\n    title,\n    sections[] {\n      _type,\n      _key,\n      _type == "hero" => {\n        title,\n        subtitle,\n        "imageUrl": image.asset->url\n      },\n      _type == "moodPicker" => {\n        title,\n        subtitle\n      },\n      _type == "featuredPosts" => {\n        title,\n        count\n      },\n      _type == "textContent" => {\n        heading,\n        content,\n        align\n      }\n    },\n    seo\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc, _id desc)[0...12] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    "author": author->{_id, name, slug, "image": image.asset->url, imageUrl},\n    "location": location->{_id, name, slug, "image": image.asset->url, imageUrl},\n    "mainImage": mainImage.asset->url,\n    imageUrl,\n    "categories": categories[]->{_id, title, "slug": slug.current},\n    "mood": mood->{_id, title, slug, colorStart, colorEnd}\n  }\n': INITIAL_POSTS_QUERY_RESULT;
    '\n  *[_type == "mood"] | order(title asc) {\n    _id,\n    title,\n    slug,\n    description,\n    colorStart,\n    colorEnd\n  }\n': MOODS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    "author": author->{_id, name, slug, "image": image.asset->url, imageUrl},\n    "location": location->{_id, name, slug, "image": image.asset->url, imageUrl},\n    "mainImage": mainImage.asset->url,\n    imageUrl,\n    "categories": categories[]->{_id, title, "slug": slug.current},\n    "mood": mood->{_id, title, colorStart, colorEnd},\n    body\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current != $slug && (\n    author._ref == $authorId || \n    location._ref == $locationId || \n    count(categories[@._ref in $categoryIds]) > 0\n  )] | order(publishedAt desc)[0...3] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    "mainImage": mainImage.asset->url,\n    imageUrl,\n    "mood": mood->{_id, title, colorStart, colorEnd}\n  }\n': SIMILAR_POSTS_QUERY_RESULT;
  }
}
